<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT glossary (Code+, Version+, DatePublication+, Title+, LabelXml+, BlocFonctionnel+, Description+, DomaineDeDefinition+, Reference+, Type+, Longueur+, Presence+, Format+, Anomalie+)>
     <!ELEMENT List (glossary+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Version (#PCDATA)>
     <!ELEMENT DatePublication (#PCDATA)>
     <!ELEMENT Title (#PCDATA)>
     <!ELEMENT LabelXml (#PCDATA)>
     <!ELEMENT BlocFonctionnel (#PCDATA)>
     <!ELEMENT Description (#PCDATA)>
     <!ELEMENT DomaineDeDefinition (#PCDATA)>
     <!ELEMENT Reference (#PCDATA)>
     <!ELEMENT Type (#PCDATA)>
     <!ELEMENT Longueur (#PCDATA)>
     <!ELEMENT Presence (#PCDATA)>
     <!ELEMENT Format (#PCDATA)>
     <!ELEMENT Anomalie (CodeAnomalie+,IntituleAnomalie+,GraviteAnomalie+)>
     <!ELEMENT CodeAnomalie (#PCDATA)>
     <!ELEMENT IntituleAnomalie (#PCDATA)>
     <!ELEMENT GraviteAnomalie (#PCDATA)>
]>
<List>
     <glossary>
          <Code>00013</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>ANNÉE - TRIMESTRE</Title>
          <LabelXml>Quarter</LabelXml>
          <BlocFonctionnel>Déclaration employeur - Identification</BlocFonctionnel>
          <Description>Détermination de l'année et du trimestre.
Détermination de l'année et du trimestre de la déclaration.</Description>
          <DomaineDeDefinition>Si la demande de consultation concerne une DfmA, la valeur renseignée doit être comprise entre le premier trimestre 2003 (20031) et le dernier trimestre civil échu (AAAAT en cours -1).
Si la demande de consultation concerne une DmfAPPL, la valeur renseignée doit être comprise entre le premier trimestre 2005 (20051) et le dernier trimestre civil échu (AAAAT en cours -1).</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>5</Longueur>
          <Presence>Indispensable </Presence>
          <Format>AAAAT
. AAAA est l'année
. T est le trimestre</Format>
          <Anomalie>
               <CodeAnomalie>00013-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-003</CodeAnomalie>
               <IntituleAnomalie>Invalide</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00032</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>BOÎTE AUX LETTRES DU TRAVAILLEUR</Title>
          <LabelXml>WorkerPostBox</LabelXml>
          <BlocFonctionnel>Personne physique</BlocFonctionnel>
          <Description>Numéro de boîte aux lettres.
Numéro de boîte aux lettres du domicile du travailleur.Cette donnée ne peut plus être utilisée.</Description>
          <DomaineDeDefinition></DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>4</Longueur>
          <Presence>Interdit </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00032-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00032-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00032-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00032-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00032-005</CodeAnomalie>
               <IntituleAnomalie>Interdit</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00019</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>CATÉGORIE DE L'EMPLOYEUR POUR LAQUELLE UNE COTISATION NON LIÉE À UNE PERSONNE PHYSIQUE EST DUE</Title>
          <LabelXml>UnrelatedEmployerClass</LabelXml>
          <BlocFonctionnel>Cotisation non liée à une personne physique - Identification</BlocFonctionnel>
          <Description>L'indice de catégorie permet de différencier les employeurs selon leurs obligations en fonction de particularités propres à l'activité exercée. Il est attribué par l'ONSS.
Il s'agit ici de déclarer la catégorie de l'employeur pour laquelle une cotisation non liée à une personne physique est due.</Description>
          <DomaineDeDefinition>Nombre de 3 chiffres attribué par l'ONSS.
Pour les valeurs admises pour une administration provinciale ou locale, voir l'annexe 29 - Liste des indices des différentes catégories d'employeurs APL ; uniquement les catégories pour lesquelles le code présence est égal à 4 ou 6.</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>3</Longueur>
          <Presence>Indispensable </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00019-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00019-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00019-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00019-034</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité trimestre</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00019-051</CodeAnomalie>
               <IntituleAnomalie>Non repris au répertoire pour le trimestre de déclaration</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00019-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00019-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00019-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00019-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00169</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>CODE PAYS DU LIEU DE NAISSANCE DU TRAVAILLEUR</Title>
          <LabelXml>WorkerBirthplaceCountry</LabelXml>
          <BlocFonctionnel>Personne physique</BlocFonctionnel>
          <Description>Code permettant d'identifier un pays.
Code permettant de déterminer de façon unique le pays du lieu de naissance de la personne physique.Cette donnée ne peut plus être utilisée.</Description>
          <DomaineDeDefinition>Voir Annexe 5 - Liste des codes pays.
</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>5</Longueur>
          <Presence>Interdit </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00169-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00169-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00169-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00169-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00169-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00169-005</CodeAnomalie>
               <IntituleAnomalie>Interdit</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00035</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>CODE PAYS DU TRAVAILLEUR</Title>
          <LabelXml>WorkerCountry</LabelXml>
          <BlocFonctionnel>Personne physique</BlocFonctionnel>
          <Description>Code permettant d'identifier un pays.
Code permettant d'identifier le pays où est domicilié le travailleur.Cette donnée ne peut plus être utilisée.</Description>
          <DomaineDeDefinition>Voir Annexe 5 - Liste des codes pays.
</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>5</Longueur>
          <Presence>Interdit </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00035-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00035-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00035-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00035-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00035-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00035-005</CodeAnomalie>
               <IntituleAnomalie>Interdit</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00033</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>CODE POSTAL DU TRAVAILLEUR</Title>
          <LabelXml>WorkerZIPCode</LabelXml>
          <BlocFonctionnel>Personne physique</BlocFonctionnel>
          <Description>Numéro postal d'une commune.
Numéro postal de l'adresse où le travailleur est domicilié.
Pour les travailleurs domiciliés en Belgique, il faut utiliser la liste officielle des codes postaux belges.Cette donnée ne peut plus être utilisée.</Description>
          <DomaineDeDefinition></DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>9</Longueur>
          <Presence>Interdit </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00033-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00033-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00033-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00033-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00033-005</CodeAnomalie>
               <IntituleAnomalie>Interdit</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00020</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>CODE TRAVAILLEUR POUR UNE COTISATION QUI N'EST PAS LIÉE À UNE PERSONNE PHYSIQUE</Title>
          <LabelXml>UnrelatedWorkerCode</LabelXml>
          <BlocFonctionnel>Cotisation non liée à une personne physique - Identification</BlocFonctionnel>
          <Description>Ce code travailleur permet d'identifier une cotisation qui n'est pas liée à une personne physique mais qui est due au niveau de l'indice de catégorie de l'employeur.</Description>
          <DomaineDeDefinition>Les codes travailleur correspondant à une cotisation non liée à une personne physique (voir annexe 2 - Liste des codes travailleurs pour lesquels des cotisations sont dues).Pour une administration provinciale ou locale, les codes travailleurs sont repris dans l'annexe 28.</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>3</Longueur>
          <Presence>Indispensable </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00020-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00020-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00020-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00020-035</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité trimestre - catégorie employeur</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00020-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00020-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00020-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00020-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00168</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>COMMUNE - LIEU DE NAISSANCE DU TRAVAILLEUR</Title>
          <LabelXml>WorkerBirthplace</LabelXml>
          <BlocFonctionnel>Personne physique</BlocFonctionnel>
          <Description>Nom d'une commune.
Nom de la commune du lieu de naissance de la personne physique.Cette donnée ne peut plus être utilisée.</Description>
          <DomaineDeDefinition></DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>40</Longueur>
          <Presence>Interdit </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00168-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00168-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00168-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00168-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00168-005</CodeAnomalie>
               <IntituleAnomalie>Interdit</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00034</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>COMMUNE DU TRAVAILLEUR</Title>
          <LabelXml>WorkerCity</LabelXml>
          <BlocFonctionnel>Personne physique</BlocFonctionnel>
          <Description>Nom d'une commune.
Nom de la commune de domiciliation du travailleur.Cette donnée ne peut plus être utilisée.</Description>
          <DomaineDeDefinition>
S'il s'agit d'une commune belge, la valeur doit référer à un des noms qui correspond en annexe 23 au code postal indiqué dans la zone 00033 [Code postal du travailleur].</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>40</Longueur>
          <Presence>Interdit </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00034-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00034-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00034-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00034-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00034-005</CodeAnomalie>
               <IntituleAnomalie>Interdit</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00218</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>DATE DE CRÉATION DU FORMULAIRE</Title>
          <LabelXml>FormCreationDate</LabelXml>
          <BlocFonctionnel>Formulaire</BlocFonctionnel>
          <Description>
Date à laquelle le formulaire est créé.</Description>
          <DomaineDeDefinition>
AAAA est un élément de [année en cours -1 ; année en cours] ;
La date ne peut pas se trouver dans le futur.</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>10</Longueur>
          <Presence>Indispensable </Presence>
          <Format>AAAA-MM-JJ
· AAAA est l'année 
· MM est le mois 
. JJ est le jour</Format>
          <Anomalie>
               <CodeAnomalie>00218-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00218-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00218-003</CodeAnomalie>
               <IntituleAnomalie>Invalide</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00218-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00218-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00218-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00218-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00028</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>DATE DE NAISSANCE DU TRAVAILLEUR</Title>
          <LabelXml>WorkerBirthdate</LabelXml>
          <BlocFonctionnel>Personne physique</BlocFonctionnel>
          <Description>Date de naissance de la personne physique.Cette donnée ne peut plus être utilisée.</Description>
          <DomaineDeDefinition>AAAA est un élément de [année de la déclaration-120; année de la déclaration]. </DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>10</Longueur>
          <Presence>Interdit </Presence>
          <Format>AAAA-MM-JJ (date valide)
AAAA-00-00</Format>
          <Anomalie>
               <CodeAnomalie>00028-003</CodeAnomalie>
               <IntituleAnomalie>Invalide</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00028-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00028-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00028-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00028-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00028-005</CodeAnomalie>
               <IntituleAnomalie>Interdit</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00852</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>ENVOI DES ANOMALIES</Title>
          <LabelXml>AnomalySubmission</LabelXml>
          <BlocFonctionnel>Déclaration employeur - Identification</BlocFonctionnel>
          <Description>Code qui indique si l'utilisateur souhaite ou non recevoir les anomalies </Description>
          <DomaineDeDefinition>0 = ne pas envoyer les anomalies
1 = envoyer les anomalies</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>1</Longueur>
          <Presence>Facultative </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00852-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00852-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00852-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00852-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00852-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00852-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00299</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>HEURE PRÉCISE DE CRÉATION DU FORMULAIRE</Title>
          <LabelXml>FormCreationHour</LabelXml>
          <BlocFonctionnel>Formulaire</BlocFonctionnel>
          <Description>Moment précis, exprimé en heures, minutes, secondes et millièmes de secondes.
</Description>
          <DomaineDeDefinition>HH est un élément de  [00;23]
MM est un élément de [00;59]
SS est un élément de [00;59]
SSS un élément de [000;999]
</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>12</Longueur>
          <Presence>Indispensable </Presence>
          <Format>HH:MM:SS.SSS
. HH sont les heures
. MM sont les minutes
. SS sont les secondes
. SSS sont les millièmes de secondes</Format>
          <Anomalie>
               <CodeAnomalie>00299-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00299-003</CodeAnomalie>
               <IntituleAnomalie>Invalide</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00299-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00299-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00299-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>