<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT glossary (Code+, Version+, DatePublication+, Title+, LabelXml+, BlocFonctionnel+, Description+, DomaineDeDefinition+, Reference+, Type+, Longueur+, Presence+, Format+, Anomalie+)>
     <!ELEMENT List (glossary+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Version (#PCDATA)>
     <!ELEMENT DatePublication (#PCDATA)>
     <!ELEMENT Title (#PCDATA)>
     <!ELEMENT LabelXml (#PCDATA)>
     <!ELEMENT BlocFonctionnel (#PCDATA)>
     <!ELEMENT Description (#PCDATA)>
     <!ELEMENT DomaineDeDefinition (#PCDATA)>
     <!ELEMENT Reference (#PCDATA)>
     <!ELEMENT Type (#PCDATA)>
     <!ELEMENT Longueur (#PCDATA)>
     <!ELEMENT Presence (#PCDATA)>
     <!ELEMENT Format (#PCDATA)>
     <!ELEMENT Anomalie (CodeAnomalie+,IntituleAnomalie+,GraviteAnomalie+)>
     <!ELEMENT CodeAnomalie (#PCDATA)>
     <!ELEMENT IntituleAnomalie (#PCDATA)>
     <!ELEMENT GraviteAnomalie (#PCDATA)>
]>
<List>
     <glossary>
          <Code>00041</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>ACTIVITÉ PAR RAPPORT AU RISQUE</Title>
          <LabelXml>ActivityWithRisk</LabelXml>
          <BlocFonctionnel>Ligne travailleur</BlocFonctionnel>
          <Description>Code se référant à la nomenclature des classes de risques génériques utilisées par les entreprises d'assurance pour la détermination des primes Accidents du Travail (AT). Les conditions précises de déclaration sont reprises dans le document des instructions DMFA à destination des employeurs.

Une activité est renseignée au niveau d'un travailleur lorsque celle-ci s'écarte de l'activité principale de l'entreprise et qu'elle a nécessité de facto une tarification spécifique reprise au niveau du contrat d'assurance Accidents du Travail.

Si la classe de risque du travailleur sur lequel porte la déclaration change en cours du trimestre, il y a lieu de déclarer la classe de risque au dernier jour du trimestre ou au dernier jour d'occupation pour le statut qui est déclaré. Ainsi un " ouvrier en atelier" qui devient " ouvrier sur chantier " sera déclaré comme " ouvrier sur chantier ". Un " ouvrier en atelier " qui devient " employé sédentaire " sera connu comme " ouvrier en atelier" pour la déclaration en tant qu'ouvrier et comme " employé sédentaire" pour la déclaration en tant qu'employé.

Elle est également nécessaire lorsqu'elle concerne un sportif. Elle sert alors aussi au calcul de la rémunération de base.
</Description>
          <DomaineDeDefinition>La liste des valeurs admises se trouve en annexe 6 - Activité par rapport au risque.
</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>3</Longueur>
          <Presence>Obligatoire si l'activité du travailleur par
rapport au risque s'écarte de l'activité principale
de  l'entreprise et qu'elle a nécessité de
facto une tarification spécifique reprise au niveau 
du contrat d'assurance Accidents du Travail.</Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00041-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00041-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00041-025</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité catégorie employeur</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00041-030</CodeAnomalie>
               <IntituleAnomalie>Incompatibilité code travailleur</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00041-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00041-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00041-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00041-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>01237</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>AIDE RÉGIONALE À L'EMPLOI</Title>
          <LabelXml>RegionalAidMeasure</LabelXml>
          <BlocFonctionnel>Occupation - Informations</BlocFonctionnel>
          <Description>Code qui indique que l'occupation du travailleur est effectuée dans le cadre d'une aide régionale à l'emploi.</Description>
          <DomaineDeDefinition>B = Mesure de la Région Bruxelles-Capitale d'emploi d'insertion en économie sociale</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>2</Longueur>
          <Presence>Obligatoire si l'occupation du travailleur est effectuée dans le cadre d'une aide régionale à l'emploi susmentionnée. 
Cette donnée ne peut pas être utilisée pour les déclarations antérieures au 1er trimestre 2021.</Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>01237-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01237-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01237-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01237-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01237-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>01222</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>ALLOCATION DE FOYER ET RÉSIDENCE MENSUELLE</Title>
          <LabelXml>MonthlyHomeIndemnity</LabelXml>
          <BlocFonctionnel>Deuxième pilier de pension - Informations</BlocFonctionnel>
          <Description>Allocation de foyer et de résidence relative au premier mois d'occupation au cours de l'année calendrier.</Description>
          <DomaineDeDefinition>Nombre entier positif et élément de [1; 99999999999].
Le montant est exprimé en eurocents.</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>11</Longueur>
          <Presence>Obligatoire si le travailleur a droit à une allocation de foyer et résidence pour le premier mois d'occupation au cours de l'année calendrier concernée.</Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>01222-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01222-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01222-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01222-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01222-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01222-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00013</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>ANNÉE - TRIMESTRE</Title>
          <LabelXml>Quarter</LabelXml>
          <BlocFonctionnel>Déclaration employeur</BlocFonctionnel>
          <Description>Détermination de l'année et du trimestre.
Détermination de l'année et du trimestre de la déclaration.</Description>
          <DomaineDeDefinition>Il doit être compris entre le premier trimestre 2003 (20031) et le dernier trimestre civil échu (AAAAT en cours -1).</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>5</Longueur>
          <Presence>Indispensable </Presence>
          <Format>AAAAT
. AAAA est l'année
. T est le trimestre</Format>
          <Anomalie>
               <CodeAnomalie>00013-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-003</CodeAnomalie>
               <IntituleAnomalie>Invalide</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00013-313</CodeAnomalie>
               <IntituleAnomalie>Attention ! Trimestre en danger de prescription ou prescrit.</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>01219</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>ANNÉE ET MOIS DE RÉFÉRENCE</Title>
          <LabelXml>ReferenceYearMonth</LabelXml>
          <BlocFonctionnel>Deuxième pilier de pension - Informations</BlocFonctionnel>
          <Description>Année et mois sur lesquels portent les éléments de salaires déclarés.</Description>
          <DomaineDeDefinition>L'année déclarée est égale à l'année de déclaration. À partir du 2019/4 le mois déclaré doit être repris dans le trimestre de déclaration.</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>7</Longueur>
          <Presence>Indispensable </Presence>
          <Format>AAAA-MM
. AAAA est l'année
. MM est le mois</Format>
          <Anomalie>
               <CodeAnomalie>01219-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01219-003</CodeAnomalie>
               <IntituleAnomalie>Invalide</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01219-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01219-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01219-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01219-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01219-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00084</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>BASE DE CALCUL DE LA COTISATION</Title>
          <LabelXml>ContributionCalculationBasis</LabelXml>
          <BlocFonctionnel>Cotisation due pour la ligne travailleur</BlocFonctionnel>
          <Description>Montant sur lequel un taux doit être appliqué afin de connaître le montant de la cotisation due pour cette ligne travailleur.</Description>
          <DomaineDeDefinition>[0;99999999999]</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>11</Longueur>
          <Presence>Obligatoire si la cotisation déclarée doit être calculée à partir d'une base de calcul sur laquelle un taux doit être appliqué.</Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00084-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-044</CodeAnomalie>
               <IntituleAnomalie>Montant calculé différent du montant déclaré</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-062</CodeAnomalie>
               <IntituleAnomalie>Zone pas d'application</IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-045</CodeAnomalie>
               <IntituleAnomalie>Montant trop élevé</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00084-046</CodeAnomalie>
               <IntituleAnomalie>Montant trop peu élevé</IntituleAnomalie>
               <GraviteAnomalie>P</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00021</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>BASE DE CALCUL DE LA COTISATION NON LIÉE À UNE PERSONNE PHYSIQUE</Title>
          <LabelXml>UnrelatedCalculationBasis</LabelXml>
          <BlocFonctionnel>Cotisation non liée à une personne physique</BlocFonctionnel>
          <Description>Montant de base qui permet de calculer le montant de la cotisation non liée à une personne physique.Aucune base de calcul ne doit être mentionnée pour la cotisation de solidarité sur l'usage d'un véhicule de société (code travailleur 862).</Description>
          <DomaineDeDefinition>[0;9999999999999]</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>13</Longueur>
          <Presence>Obligatoire si  la cotisation déclarée doit être calculée à partir d'une base de calcul.</Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00021-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00021-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00021-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00021-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00021-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00021-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00021-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00021-062</CodeAnomalie>
               <IntituleAnomalie>Zone pas d'application </IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00088</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>BASE DE CALCUL DE LA DÉDUCTION</Title>
          <LabelXml>DeductionCalculationBasis</LabelXml>
          <BlocFonctionnel>Déduction ligne travailleur</BlocFonctionnel>
          <Description>Montant sur lequel un taux doit être appliqué afin de connaître le montant de la déduction demandée pour cette ligne travailleur ou occupation.</Description>
          <DomaineDeDefinition>[0;99999999999]</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>11</Longueur>
          <Presence>Obligatoire si la déduction demandée est calculée à partir d'une base de calcul sur laquelle un taux doit être appliqué.</Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00088-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-044</CodeAnomalie>
               <IntituleAnomalie>Montant calculé différent du montant déclaré</IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-062</CodeAnomalie>
               <IntituleAnomalie>Zone pas d'application </IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00088</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>BASE DE CALCUL DE LA DÉDUCTION</Title>
          <LabelXml>DeductionCalculationBasis</LabelXml>
          <BlocFonctionnel>Déduction occupation</BlocFonctionnel>
          <Description>Montant sur lequel un taux doit être appliqué afin de connaître le montant de la déduction demandée pour cette ligne travailleur ou occupation.</Description>
          <DomaineDeDefinition>[0;99999999999]</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>11</Longueur>
          <Presence>Obligatoire si la déduction demandée est calculée à partir d'une base de calcul sur laquelle un taux doit être appliqué.</Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00088-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-044</CodeAnomalie>
               <IntituleAnomalie>Montant calculé différent du montant déclaré</IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-062</CodeAnomalie>
               <IntituleAnomalie>Zone pas d'application </IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00088-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>00032</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>BOÎTE AUX LETTRES DU TRAVAILLEUR</Title>
          <LabelXml>WorkerPostBox</LabelXml>
          <BlocFonctionnel>Personne physique</BlocFonctionnel>
          <Description>Numéro de boîte aux lettres.
Numéro de boîte aux lettres du domicile du travailleur.Cette donnée ne peut plus être utilisée.</Description>
          <DomaineDeDefinition></DomaineDeDefinition>
          <Reference></Reference>
          <Type>Alphanumérique</Type>
          <Longueur>4</Longueur>
          <Presence>Interdit </Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>00032-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00032-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00032-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00032-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>00032-005</CodeAnomalie>
               <IntituleAnomalie>Interdit</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
     </glossary>
     <glossary>
          <Code>01216</Code>
          <Version>2022/3</Version>
          <DatePublication>30/08/2022</DatePublication>
          <Title>BUDGET MOBILITÉ</Title>
          <LabelXml>MobilityBudget</LabelXml>
          <BlocFonctionnel>Occupation - Informations</BlocFonctionnel>
          <Description>Budget total qui est attribué au travailleur sur le plan de la mobilité, et qu'il peut consacrer à un ou plusieurs piliers prévus par la législation : un véhicule de société respectueux de l'environnement, modes de transports alternatifs et durables et le paiement du solde du budget.</Description>
          <DomaineDeDefinition>Nombre entier positif et élément de [1; 99999999999].
Le montant est exprimé en eurocents.</DomaineDeDefinition>
          <Reference></Reference>
          <Type>Numérique</Type>
          <Longueur>11</Longueur>
          <Presence>Obligatoire si le travailleur opte pour le budget mobilité et la partie non utilisée du solde du budget est versée au travailleur.</Presence>
          <Format></Format>
          <Anomalie>
               <CodeAnomalie>01216-001</CodeAnomalie>
               <IntituleAnomalie>Non présent</IntituleAnomalie>
               <GraviteAnomalie>NP</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01216-002</CodeAnomalie>
               <IntituleAnomalie>Non numérique</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01216-008</CodeAnomalie>
               <IntituleAnomalie>Pas dans le domaine de définition</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01216-090</CodeAnomalie>
               <IntituleAnomalie>Erreur de cardinalité</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01216-091</CodeAnomalie>
               <IntituleAnomalie>Erreur de séquence</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01216-093</CodeAnomalie>
               <IntituleAnomalie>Longueur incorrecte</IntituleAnomalie>
               <GraviteAnomalie>B</GraviteAnomalie>
          </Anomalie>
          <Anomalie>
               <CodeAnomalie>01216-146</CodeAnomalie>
               <IntituleAnomalie>Non admis</IntituleAnomalie>