<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE List [

     <!ELEMENT ann27 (Secteur?, Code?, Description?, begin_geldigheid?, einde_geldigheid?)>

     <!ELEMENT List (ann27+)>

     <!ELEMENT Secteur (#PCDATA)>

     <!ELEMENT Code (#PCDATA)>

     <!ELEMENT Description (#PCDATA)>

     <!ELEMENT begin_geldigheid (#PCDATA)>

     <!ELEMENT einde_geldigheid (#PCDATA)>

]>
<List>

<ann27>
<Secteur>Privé</Secteur>
<Code>000</Code>
<Description>Catégorie générale pour les employeurs pour lesquels l'ONSS ne perçoit aucune cotisation spéciale pour un fonds social et qui ne relèvent d'aucune autre catégorie particulière (voir aussi catégorie 011).</Description>
<begin_geldigheid>01/01/1945</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>002</Code>
<Description>Catégorie particulière pour les employeurs redevables pour les ouvriers d'une cotisation spéciale au "Fonds pour la formation des ouvriers de la Commission paritaire auxiliaire pour ouvriers" (CP n° 100) et d'aucune cotisation spéciale pour les employés (depuis le 01/07/2014, concerne notamment les activités de casino; de contrôle technique et d'évaluation de la conformité).</Description>
<begin_geldigheid>01/04/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>004</Code>
<Description>Titulaire d'un mandat politique ou public - cotisation semestrielle de solidarité. Catégorie supprimée au 31/12/1988.</Description>
<begin_geldigheid>01/01/1987</begin_geldigheid>
<einde_geldigheid>31/12/1988</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>005</Code>
<Description>Catégorie réservée aux employeurs qui occupent uniquement des étudiants non assujettis à la sécurité sociale, dans les liens d'un contrat d'occupation étudiant, et qui ne sont redevables que d'une cotisation de solidarité. Catégorie supprimée au 31/12/2009.</Description>
<begin_geldigheid>01/07/1997</begin_geldigheid>
<einde_geldigheid>31/12/2009</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>006</Code>
<Description>Employeurs pour lesquels, en vertu de la loi du 22 février 1998, l'Office national de sécurité sociale assure la perception et le recouvrement des cotisations qui jusqu'à la date du 30/09/1998 étaient perçues par le Fonds de retraite des ouvriers mineurs.</Description>
<begin_geldigheid>01/10/1998</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>007</Code>
<Description>Intermédiaires en services bancaires et en services d'investissement, inscrits auprès de la FSMA.</Description>
<begin_geldigheid>01/01/2016</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>010</Code>
<Description>Catégorie générale pour les employeurs redevables pour leurs employés d'une cotisation au "Fonds social de la CPAE" (Commission paritaire auxiliaire pour employés n° 200 compétente pour le secteur marchand) et pour lesquels l'ONSS ne perçoit pour leurs ouvriers aucune cotisation spéciale pour un fonds social (voir aussi catégorie 210).</Description>
<begin_geldigheid>01/07/1975</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>011</Code>
<Description>Catégorie générale réservée aux employeurs "sans but de lucre" pour lesquels l'ONSS ne perçoit aucune cotisation spéciale pour un fonds social et qui ne relèvent d'aucune catégorie particulière ; catégorie réservée aux employeurs qui relèvent principalement de la CP n° 335 et qui ne relèvent d'aucune autre catégorie particulière (voir aussi catégorie 000).</Description>
<begin_geldigheid>01/07/1975</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>012</Code>
<Description>Catégorie réservée aux employeurs étrangers sans siège d'exploitation en Belgique redevables : pour leurs employés : d'une cotisation au "Fonds social de la CPAE" (CP n° 200 compétente pour le secteur marchand) et, à partir du 01/04/2012, pour les ouvriers : d'une cotisation au "Fonds pour la formation des ouvriers de la Commission paritaire auxiliaire pour ouvriers" (CP n° 100).</Description>
<begin_geldigheid>01/07/1975</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>013</Code>
<Description>Employeurs relevant  pour les ouvriers et certains employés de la Commission paritaire de l'industrie et du commerce du diamant n° 324 ; non redevables pour les ouvriers des entreprises commerciales de la cotisation de base au Fonds de fermeture d'entreprises ; pour certains employés : redevables d'une cotisation au Fonds de la Commission paritaire n° 200 CPAE.</Description>
<begin_geldigheid>01/01/1945</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>014</Code>
<Description>Employeurs relevant de la Commission paritaire des ports n° 301 et/ou des Sous commissions paritaires 301.01, 301.02, 301.03 et 301.05.</Description>
<begin_geldigheid>01/01/1945</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>015</Code>
<Description>Employeurs relevant de la Commission paritaire de l'industrie de la réparation des navires. Catégorie supprimée au 30/06/2005. Employeurs repris en catégorie 000 à partir du 01/07/2005.</Description>
<begin_geldigheid>01/01/1945</begin_geldigheid>
<einde_geldigheid>30/06/2005</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>016</Code>
<Description>Employeurs, exclusivement de type non-commercial, redevables d'une cotisation au Fonds de la Commission paritaire de l'industrie hôtelière n° 302 ; à partir du 01/07/2007, à l'exclusion des travailleurs occasionnels déclarés dans une autre catégorie (voir aussi catégories 116, 216, 017, 117, 217). Catégorie supprimée au 30/09/2013.</Description>
<begin_geldigheid>01/07/1981</begin_geldigheid>
<einde_geldigheid>30/09/2013</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>017</Code>
<Description>Employeurs, de type commercial ou non-commercial, redevables d'une cotisation au Fonds de la Commission paritaire de l'industrie hôtelière n° 302 ; à l'exclusion des travailleurs occasionnels déclarés dans la catégorie 317.</Description>
<begin_geldigheid>01/04/1979</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>018</Code>
<Description>Employeurs occupant des travailleurs à domicile et ne cotisant pas pour leurs employés au "Fonds social". Catégorie supprimée au 31/03/1988. Employeurs repris en catégorie 000 à partir du 01/04/1988.</Description>
<begin_geldigheid>01/07/1975</begin_geldigheid>
<einde_geldigheid>31/03/1988</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>019</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire n° 143 de la pêche maritime - "Zeevissersfonds" ; catégorie réservée au personnel navigant ; les travailleurs liés par un contrat d'engagement pour la pêche maritime sont à déclarer selon un mode particulier pour leurs rémunérations (forfaitaires) et leurs prestations (voir aussi catégories 086, 186).</Description>
<begin_geldigheid>01/01/1946</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>020</Code>
<Description>Employeurs occupant des travailleurs rémunérés totalement ou partiellement au pourboire, qui ne relèvent pas de la Commission paritaire de l'industrie hôtelière n° 302 et qui ne sont pas redevables de la cotisation de base au "Fonds de fermeture d'entreprises". Catégorie supprimée au 31/03/2007.</Description>
<begin_geldigheid>01/07/1981</begin_geldigheid>
<einde_geldigheid>30/06/2007</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>021</Code>
<Description>Employeurs relevant de la Commission paritaire n° 139 de la batellerie occupant des travailleurs liés par un contrat d'engagement pour le service des bâtiments de navigation intérieure.</Description>
<begin_geldigheid>01/01/1945</begin_geldigheid>
<einde_geldigheid>31/12/2015</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>022</Code>
<Description>Employeurs relevant de la Sous commission paritaire pour les établissements et services de santé n° 305.02, redevables d'une cotisation au "Fonds social pour le secteur des milieux d'accueil d'enfants" (sous secteur 305.02.09) ; concerne les employeurs "francophones et germanophones" situés dans la Région wallonne ou dans la Région de Bruxelles-Capitale dont l'activité consiste en "l'accueil des enfants" ; non redevables de la cotisation de base au "Fonds de fermetures d'entreprises" (voir aussi catégorie 322) ; jusqu'au 31/12/2007.</Description>
<begin_geldigheid>01/01/1990</begin_geldigheid>
<einde_geldigheid>31/12/2007</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>022</Code>
<Description>A partir du 01/01/2008, employeurs ressortissant à la Commission paritaire n° 332 pour "le Secteur francophone et germanophone de l'aide sociale et des soins de santé" (sous-secteur 332.00.10) ; redevables d'une cotisation au "Fonds social pour le secteur des milieux d'accueil d'enfants" ; concerne les employeurs francophones et germanophones situés en Région wallonne ou bruxelloise dont l'activité principale concerne l'accueil des enfants jusque 12 ans : milieu d'accueil d'enfants, accueil extra-scolaire, crèche, crèche parentale, garde d'enfants malades, maison communale d'accueil d'enfance, maison d'enfants, milieu d'accueil occasionnel, milieu d'accueil régulier à horaire flexible, milieu d'accueil d'urgence, halte-garderie, farandoline, halte-accueil, prégardiennat, services de gardiennes agréées et service d'accueillantes d'enfants conventionnées (voir aussi catégories 322, 722).</Description>
<begin_geldigheid>01/01/2008</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>023</Code>
<Description>Employeurs occupant des travailleurs rémunérés totalement ou partiellement au pourboire, qui ne relèvent pas de la Commission paritaire de l'industrie hôtelière n° 302 et qui sont redevables de la cotisation de base au "Fonds de fermeture d'entreprises". Catégorie supprimée au 31/03/2007.</Description>
<begin_geldigheid>01/04/1947</begin_geldigheid>
<einde_geldigheid>30/06/2007</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>024</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire de la construction n° 124 dont l'activité principale consiste en travaux de gros oeuvre en général (voir aussi catégories 026, 044, 054).</Description>
<begin_geldigheid>01/01/1947</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>025</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Sous commission paritaire pour les hôpitaux privés n° 305.01 ; concerne les établissements soumis à la loi sur les hôpitaux du 23/12/1963 et les maisons de soins psychiatriques, jusqu'au 31/12/2007.</Description>
<begin_geldigheid>01/01/1990</begin_geldigheid>
<einde_geldigheid>31/12/2007</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>025</Code>
<Description>A partir du 01/01/2008, employeurs ressortissant à la Commission paritaire n° 330 pour les Etablissements et services de santé (sous-secteur 330.01.10) ; redevables d'une cotisation au "Fonds social pour les hôpitaux privés" ; concerne les hôpitaux privés soumis à la loi du 07/08/1987 et les maisons de soins psychiatriques (voir aussi catégories 072, 111).</Description>
<begin_geldigheid>01/01/2008</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>026</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire de la construction n° 124 dont l'activité principale consiste en travaux de parachèvement en général (notamment peinture, isolation, installations sanitaires, de chauffage, d'objet en bois, d'éléments préfabriqués, vitrerie, charpenterie...), en commerce de gros de matériaux de construction... (voir aussi catégories 024, 044, 054).</Description>
<begin_geldigheid>01/10/1949</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>027</Code>
<Description>Catégorie réservée uniquement à la déclaration des cotisations personnelles dues par les victimes d'un accident de travail survenu après le 15/10/1951 qui doivent être versées par les employeurs qui sont leur propre assureur et par les organismes d'assurances.</Description>
<begin_geldigheid>01/10/1951</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>028</Code>
<Description>Catégorie réservée uniquement à la déclaration des cotisations personnelles dues par les victimes d'une maladie professionnelle dont l'indemnisation a été demandée après le 15/10/1951.</Description>
<begin_geldigheid>01/01/1954</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>029</Code>
<Description>Employeurs ressortissant de la Sous commission paritaire pour les exploitations forestières (SCP n° 125.01) qui sont redevables d'une cotisation en faveur du Fonds pour la sécurité d'existence des exploitations forestières. (voir aussi cat. 129, 229).</Description>
<begin_geldigheid>01/07/1955</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>030</Code>
<Description>Catégorie réservée aux employeurs ressortissants de la CP 310 (banques) ou de la CP 326 (industrie du gaz et de l'électricité) non redevables ni pour les ouvriers, ni pour les employés, d'aucune cotisation spéciale à aucun fonds social.</Description>
<begin_geldigheid>01/07/1981</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>031</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire des maîtres-tailleurs, des tailleuses et couturières n° 107 (voir aussi catégorie 038).</Description>
<begin_geldigheid>01/07/1982</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>032</Code>
<Description>Ambassades et consulats redevables à partir du 01-04-2018 d'une cotisation au Fonds social auxiliaire du non-marchand.</Description>
<begin_geldigheid>01/01/1963</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>033</Code>
<Description>Catégorie réservée uniquement à certains services de compensation redevables des cotisations de sécurité sociale sur les salaires pour jours fériés qu'ils paient, en tant que tiers-payants, au nom et pour compte des employeurs (autres que les Fonds de sécurité d'existence et la Caisse nationale des vacances de l'industrie diamantaire).</Description>
<begin_geldigheid>01/01/1957</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>034</Code>
<Description>Application de la loi du 28/06/1960 relative à la sécurité sociale des personnes ayant effectué des services temporaires à l'armée. Catégorie supprimée au 31/12/2003.</Description>
<begin_geldigheid>15/07/1960</begin_geldigheid>
<einde_geldigheid>31/12/2003</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>035</Code>
<Description>Catégorie réservée aux employeurs exerçant une profession libérale, c-à-d. les médecins, les dentistes, les vétérinaires, les avocats, les notaires, les architectes, les huissiers de justice, les professions paramédicales, les géomètres-experts, les réviseurs d'entreprises et les experts-comptables, les associations de fait formées par ces personnes ainsi que les sociétés qui sont créées dans le cadre de l'exercice de ces professions ; à l'exclusion des pharmaciens ; non redevables de la cotisation de base au "Fonds de fermeture d'entreprises" ; non redevables d'aucune cotisation de sécurité d'existence; mais bénéficiaires de la redistribution des charges sociales (voir aussi catégories 135, 235, 335 pour les pharmaciens) ; jusqu'au 31/12/2007.</Description>
<begin_geldigheid>01/01/1987</begin_geldigheid>
<einde_geldigheid>31/12/2007</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>035</Code>
<Description>Employeurs redevables, à partir du 01/07/2012, d'une cotisation au Fonds de la Commission paritaire pour les professions libérales n° 336 ; catégorie réservée aux professions libérales au sens strict, non médicales, et bénéficiaires de la redistribution des charges sociales, c-à-d. vétérinaire, avocat, architecte, huissier de justice, géomètre-expert, réviseur d'entreprise, comptable, expert-comptable, les associations de fait formées par ces personnes ainsi que les sociétés qui sont créées dans le cadre de l'exercice de ces professions (voir aussi catégories 135, 435, 735, 835).</Description>
<begin_geldigheid>01/01/2008</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>036</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire de l'imprimerie, des arts graphiques et des journaux n° 130.</Description>
<begin_geldigheid>01/10/1960</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>037</Code>
<Description>Employeurs, personnes physiques, occupant du personnel domestique, redevables d'une cotisation au Fonds de la Commission paritaire pour la gestion d'immeubles, les agents immobiliers et les travailleurs domestiques n° 323 (voir aussi cat. 039 "personnel de maison").</Description>
<begin_geldigheid>01/01/1970</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>038</Code>
<Description>Employeurs redevables d'une cotisation aux Fonds des Commissions paritaires de l'industrie de l'habillement et de la confection n° 109 et/ou n° 215 (voir aussi catégorie 031).</Description>
<begin_geldigheid>01/01/1961</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>039</Code>
<Description>Employeurs, personnes physiques, qui occupent du "personnel de maison", autres que des travailleurs domestiques ; à partir du 01/01/2008, relèvent de la Commission paritaire pour le secteur non-marchand n° 337 ou de la Commission paritaire pour les entreprises forestières n° 146 ; en sont exclus les employeurs, qui relèvent des Commissions paritaires n° 144 de l'agriculture et n° 145 pour les entreprises horticoles (voir aussi cat. 094, 193 et 037).</Description>
<begin_geldigheid>01/01/1988</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>041</Code>
<Description>Application de l'arrêté royal dispensant certaines catégories de personnes ayant exercé leur activité professionnelle, soit au Congo, soit au Rwanda - Burundi, des conditions d'admission à l'assurance chômage et à l'assurance maladie - invalidité. Catégorie supprimée au 31/12/2002.</Description>
<begin_geldigheid>01/07/1962</begin_geldigheid>
<einde_geldigheid>31/12/2002</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>043</Code>
<Description>Catégorie réservée au personnel auxiliaire occupé par les Communautés européennes. Perception des cotisations de sécurité sociale limitées à celles afférentes aux régimes de pension, de l'assurance maladie-invalidité et du chômage.</Description>
<begin_geldigheid>01/01/1962</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>044</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire de la construction n° 124 dont l'activité principale consiste à exécuter des travaux de carrelage, de mosaïque et tous autres travaux de revêtement des murs et du sol (le bois excepté), travaux de plafonnage et d'enduits, travaux de stuc et de staff (voir aussi catégories 024, 026, 054).</Description>
<begin_geldigheid>01/07/1962</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>048</Code>
<Description>Employeurs redevables d'une cotisation aux Fonds des Commissions paritaires de l'industrie alimentaire n° 118 et/ou n° 220 et non repris dans une autre catégorie particulière à ce secteur (voir aussi catégories 051, 052, 058, 258, 848).</Description>
<begin_geldigheid>01/04/1964</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>049</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire pour l'entretien du textile n° 110.</Description>
<begin_geldigheid>01/10/1964</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>051</Code>
<Description>Employeurs redevables d'une cotisation aux Fonds des Commissions paritaires de l'industrie alimentaire n° 118 et/ou n° 220 - sous secteur de l'industrie des légumes (conserves, surgelés, légumes secs, déshydratés, nettoyage ou préparation de légumes frais...) (voir aussi catégories 052, 048, 058, 258, 848).</Description>
<begin_geldigheid>01/04/1984</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>052</Code>
<Description>Employeurs redevables d'une cotisation aux Fonds des Commissions paritaires de l'industrie alimentaire  n° 118 et/ou n° 220 - sous secteur de l'industrie des fruits (conserves, surgelés, confitures, sirops...) (voir aussi catégories 051, 048, 058, 258, 848).</Description>
<begin_geldigheid>01/04/1984</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>053</Code>
<Description>Employeurs relevant des Commissions paritaires n° 101 - Commission nationale mixte des mines et n° 205 pour employés des charbonnages - concerne les mines de houille, les usines de sous-produits, les organismes dépendant des mines...</Description>
<begin_geldigheid>01/07/1972</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>054</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire de la construction n° 124 dont l'activité principale réside dans l'exécution des travaux de couverture de construction et de travaux de rejointoiement (voir aussi catégories 024, 026, 044).</Description>
<begin_geldigheid>01/07/1962</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>055</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire de l'ameublement et de l'industrie transformatrice du bois n° 126.</Description>
<begin_geldigheid>01/01/1965</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>056</Code>
<Description>Employeurs relevant des Commissions paritaires n° 104 de l'industrie sidérurgique et n° 210 des employés de l'industrie sidérurgique.</Description>
<begin_geldigheid>01/01/1964</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>057</Code>
<Description>Employeurs redevables pour les ouvriers de cotisations aux Fonds de la CP du commerce alimentaire n° 119, et pour les employés de la CP du commerce de détail indépendant n° 201 - concerne le petit commerce de détail alimentaire occupant moins de 20 travailleurs (en moyenne au cours de l'année civile précédente) (voir aussi catégorie 157).</Description>
<begin_geldigheid>01/04/1966</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>058</Code>
<Description>Boulangerie (ou pâtisserie) artisanale : boulangerie (ou pâtisserie) qui fabrique des produits frais de consommation immédiate à très court délai de conservation et les salons de consommation annexés à une pâtisserie dont le nombre d'ouvriers employés est inférieur à 20 (exprimés en équivalents temps plein); redevable pour les ouvriers d'une cotisation au "Fonds social et de garantie de la boulangerie, pâtisserie et salons de consommation annexés", et pour les employés au fonds de la CP du commerce de détail indépendant n° 201.</Description>
<begin_geldigheid>01/04/1966</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>059</Code>
<Description>Employeurs relevant de la Sous commission paritaire de la fabrication industrielle et de la fabrication artisanale de fourrure n° 148.03. Catégorie supprimée au 30/06/2014 (voir aussi catégorie 169).</Description>
<begin_geldigheid>01/10/1966</begin_geldigheid>
<einde_geldigheid>30/06/2014</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>060</Code>
<Description>Employeurs relevant de la Commission paritaire pour les services de gardiennage et/ou de surveillance n° 317.</Description>
<begin_geldigheid>01/01/1980</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>061</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire de l'industrie verrière n° 115.</Description>
<begin_geldigheid>01/01/1987</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>062</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Sous commission paritaire des établissements et services d'éducation et d'hébergement de la communauté flamande n° 319.01 ; concerne les employeurs agréés et/ou subsidiés par la Communauté flamande ou la Commission communautaire flamande (voir aussi catégories 162, 462).</Description>
<begin_geldigheid>01/10/1989</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>063</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Sous commission paritaire de l'industrie des carrières de kaolin et de sables, exploitées à ciel ouvert, des provinces de Brabant wallon, de Hainaut, de Liège, de Luxembourg et de Namur n° 102.05 (voir aussi catégories 463, 090, 010).</Description>
<begin_geldigheid>01/04/1967</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>064</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire des entreprises de garages n° 112 (voir aussi catégorie 065).</Description>
<begin_geldigheid>01/07/1967</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>065</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Sous commission paritaire pour la carrosserie n° 149.02 (voir aussi catégorie 064).</Description>
<begin_geldigheid>01/01/1968</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>066</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire pour les entreprises de nettoyage n° 121.</Description>
<begin_geldigheid>01/10/1968</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>067</Code>
<Description>Employeurs redevables pour les ouvriers d'une cotisation au Fonds de la Sous-commission paritaire des électriciens : installation et distribution, n° 149.01 ; et pour les employés de la CP du commerce de détail indépendant n° 201, à l'exclusion de ceux relevant de la catégorie 467 (voir aussi catégorie 467).</Description>
<begin_geldigheid>01/04/1969</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>068</Code>
<Description>Employeurs relevant de la Commission paritaire du transport et de la logistique n° 140 et redevables d'une cotisation au "Fonds social des entreprises de taxi et des services de location de voitures avec chauffeur" (voir aussi catégories 083, 084, 085, 283).</Description>
<begin_geldigheid>01/07/1969</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>069</Code>
<Description>Fabrication/réparation des chaussures, pantoufles, bottiers, chausseurs - voir CP employés 200.</Description>
<begin_geldigheid>01/07/1970</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann27>
<ann27>
<Secteur>Privé</Secteur>
<Code>070</Code>
<Description>Employeurs redevables d'une cotisation au Fonds de la Commission paritaire Nationale des Sports n° 223 ; catégorie réservée uniquement, à partir du 01/07/2007, à la déclaration des sportifs rémunérés en vertu d'un contrat de travail de sportif rémunéré prévu par la loi du 24 février 1978 et des coureurs cyclistes professionnels, titulaires d'une licence délivrée par la Royale Ligue Vélocipédique Belge ASBL, et soumis à un assujettissement restreint ; concerne aussi les arbitres de football et les entraîneurs de football, de basketball, de volleyball et de cyclisme; en combinaison avec une autre catégorie attribuée aux autres sportifs et une autre catégorie attribuée aux travailleurs ordinaires (voir aussi catégories 076, 262, 362).</Description>