<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
	<!ELEMENT ann3 (Code?, Werkgeverscategorie?, Gewonebijdrage?, aantalwerknemers?, typebijdrage?, begin_geldigheid?, einde_geldigheid?)>
	<!ELEMENT List (ann3+)>
	<!ELEMENT Code (#PCDATA)>
	<!ELEMENT Werkgeverscategorie (#PCDATA)>
	<!ELEMENT Gewonebijdrage (#PCDATA)>
	<!ELEMENT aantalwerknemers (#PCDATA)>
	<!ELEMENT typebijdrage (#PCDATA)>
	<!ELEMENT begin_geldigheid (#PCDATA)>
	<!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
	<ann3>
		<Code>010</Code>
		<Werkgeverscategorie>027</Werkgeverscategorie>
		<Gewonebijdrage>Cotisation sur les paiements annuels</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/10/2019</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>015</Code>
		<Werkgeverscategorie>105, 205, 305, 505</Werkgeverscategorie>
		<Gewonebijdrage>Cotisation personnelle marins (non officiers)</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>0xx (Ouvriers)</Code>
		<Werkgeverscategorie>754</Werkgeverscategorie>
		<Gewonebijdrage>Cotisation personnelle</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/01/2022</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>0xx (Ouvriers)</Code>
		<Gewonebijdrage>Cotisation rémunérations 108%</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/01/1900</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>0xx (Ouvriers)</Code>
		<Gewonebijdrage>Cotisation rémunérations 100%</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/1900</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>260</Code>
		<Gewonebijdrage>Age à la date de début de dispense &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>260</Code>
		<Gewonebijdrage>Age à la date de début de dispense &gt;= 55 ans et &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>260</Code>
		<Gewonebijdrage>Age à la date de début de dispense &gt;= 58 ans et &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>260</Code>
		<Gewonebijdrage>Age à la date de début de dispense &gt;= 60 ans et &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>260</Code>
		<Gewonebijdrage>Age à la date de début de dispense &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>261</Code>
		<Gewonebijdrage>Age à la date de début de dispense &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>261</Code>
		<Gewonebijdrage>Age à la date de début de dispense &gt;= 55 ans et &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>261</Code>
		<Gewonebijdrage>Age à la date de début de dispense &gt;= 58 ans et &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>261</Code>
		<Gewonebijdrage>Age à la date de début de dispense &gt;= 60 ans et &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>261</Code>
		<Gewonebijdrage>Age à la date de début de dispense &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>270</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>270</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>270</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>270</Code>
		<Gewonebijdrage>Age travailleur en RCC &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>270</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>270</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>270</Code>
		<Gewonebijdrage>Age travailleur en RCC &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>271</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>271</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>271</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>271</Code>
		<Gewonebijdrage>Age travailleur en RCC &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>271</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>271</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>271</Code>
		<Gewonebijdrage>Age travailleur en RCC &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>272</Code>
		<Gewonebijdrage>Taux de base</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>30/09/2015</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>272</Code>
		<Gewonebijdrage>Taux réduit</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>30/09/2015</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>273</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>273</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>273</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>273</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>273</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>273</Code>
		<Gewonebijdrage>&lt; 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>273</Code>
		<Gewonebijdrage>&gt;= 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>274</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>274</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>274</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>274</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>274</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>274</Code>
		<Gewonebijdrage>&lt; 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>274</Code>
		<Gewonebijdrage>&gt;= 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>275</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>275</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>275</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>275</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>275</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>275</Code>
		<Gewonebijdrage>&lt; 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>275</Code>
		<Gewonebijdrage>&gt;= 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>276</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>276</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>276</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>276</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>276</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>276</Code>
		<Gewonebijdrage>&lt; 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>276</Code>
		<Gewonebijdrage>&gt;= 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>277</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>277</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>277</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>277</Code>
		<Gewonebijdrage>Age travailleur en RCC &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>277</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>277</Code>
		<Gewonebijdrage>Age travailleur en RCC &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>277</Code>
		<Gewonebijdrage>Age travailleur en RCC &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>278</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>278</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>278</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>278</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>278</Code>
		<Gewonebijdrage>Age au début du RCC ou fin de reconnaissance &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>278</Code>
		<Gewonebijdrage>&lt; 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>278</Code>
		<Gewonebijdrage>&gt;= 62 ans au début du RCC / fin reconnaissance</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>280</Code>
		<Gewonebijdrage>Taux de base</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>281</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>281</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>281</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>281</Code>
		<Gewonebijdrage>Age au début du RCIC &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>281</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>281</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>281</Code>
		<Gewonebijdrage>Age au début du RCIC &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>282</Code>
		<Gewonebijdrage>Age &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>282</Code>
		<Gewonebijdrage>Age &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>282</Code>
		<Gewonebijdrage>Age &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>282</Code>
		<Gewonebijdrage>Age &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>282</Code>
		<Gewonebijdrage>Age &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>282</Code>
		<Gewonebijdrage>Age &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>282</Code>
		<Gewonebijdrage>Age &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>283</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>283</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>283</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>283</Code>
		<Gewonebijdrage>Age au début du RCIC &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>283</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>283</Code>
		<Gewonebijdrage>Age au début du RCIC &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>283</Code>
		<Gewonebijdrage>Age au début du RCIC &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>284</Code>
		<Gewonebijdrage>Age &lt; 52 ans</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>284</Code>
		<Gewonebijdrage>Age &lt; 55 ans</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>284</Code>
		<Gewonebijdrage>Age &lt; 58 ans</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>284</Code>
		<Gewonebijdrage>Age &gt;= 60 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>31/12/2016</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>284</Code>
		<Gewonebijdrage>Age &lt; 60 ans</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/04/2012</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>284</Code>
		<Gewonebijdrage>Age &lt; 62 ans</Gewonebijdrage>
		<typebijdrage>4</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>284</Code>
		<Gewonebijdrage>Age &gt;= 62 ans</Gewonebijdrage>
		<typebijdrage>5</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>290</Code>
		<Gewonebijdrage>Taux de base</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>295</Code>
		<Gewonebijdrage>Taux de base</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>295</Code>
		<Gewonebijdrage>Taux réduit pour RCC à mi-temps ou antérieure au 01/01/1997 ou assimilé</Gewonebijdrage>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/04/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>493</Code>
		<Werkgeverscategorie>075</Werkgeverscategorie>
		<Gewonebijdrage>Personnel enseignant temporaire (sans CEP)</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/01/2014</begin_geldigheid>
		<einde_geldigheid>31/12/2014</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>493</Code>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/1900</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>495</Code>
		<Werkgeverscategorie>105, 205, 305, 505</Werkgeverscategorie>
		<Gewonebijdrage>Cotisation personelle marins (officiers)</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/01/2018</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>498 (Boursiers)</Code>
		<Werkgeverscategorie>040</Werkgeverscategorie>
		<Gewonebijdrage>Sans vacances annuelles des salariés</Gewonebijdrage>
		<typebijdrage>3</typebijdrage>
		<begin_geldigheid>01/01/2010</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>498 (Boursiers)</Code>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/1900</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>4xx (Employés)</Code>
		<Werkgeverscategorie>754</Werkgeverscategorie>
		<Gewonebijdrage>Cotisation personnelle</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/01/2022</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>4xx (Employés)</Code>
		<Gewonebijdrage>Cotisation rémunérations 100%</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/1900</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>6xx (Fonctionnaires, à l'exclusion des travailleurs statutaires exonérés des cotisations de sécurité sociale)</Code>
		<Werkgeverscategorie>754</Werkgeverscategorie>
		<Gewonebijdrage>Cotisation personnelle</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/01/2022</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>6xx (Fonctionnaires, à l'exclusion des travailleurs statutaires exonérés des cotisations de sécurité sociale)</Code>
		<Gewonebijdrage>Cotisation rémunérations 100%</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/1900</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>800</Code>
		<Gewonebijdrage>Cotisation chômage économique forfait de base</Gewonebijdrage>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>800</Code>
		<Gewonebijdrage>Cotisation chômage économique forfait réduit</Gewonebijdrage>
		<typebijdrage>2</typebijdrage>
		<begin_geldigheid>01/01/2017</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>801</Code>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/07/2021</begin_geldigheid>
		<einde_geldigheid>31/12/2021</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>803</Code>
		<Werkgeverscategorie>750, 751, 752, 753</Werkgeverscategorie>
		<typebijdrage>0</typebijdrage>
		<begin_geldigheid>01/01/2022</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>
		<Code>803</Code>
		<Werkgeverscategorie>750, 751, 752, 753</Werkgeverscategorie>
		<typebijdrage>1</typebijdrage>
		<begin_geldigheid>01/01/2022</begin_geldigheid>
		<einde_geldigheid>01/01/9999</einde_geldigheid>
	</ann3>
	<ann3>